export const GEOLOCATION = 'GEOLOCATION';
export const TABSSCREEN = 'TABSSCREEN';
export const HOMESCREEN = 'HOMESCREEN';
export const SEARCHSCREEN = 'SEARCHSCREEN';
export const NEWSSCREEN = 'NEWSSCREEN';
export const USERSCREEN = 'USERSCREEN';
export const CARDSCREEN = 'CARDSCREEN';
export const REGISTRATION_NEW_NURSE = 'REGISTRATION_NEW_NURSE';